version: '3'

services:
  grpc-client:
    build:
      context: .
      dockerfile: client/dockerfile-client.Dockerfile
    container_name: grpc-client
    image: "grpc-cli:grpc-cli"
    ports:
      - "3001:3001"
    environment:
      - IP_HOST=${IP_HOST}
    restart: always
  grpc-server:
    build:
      context: .
      dockerfile: server/dockerfile-server.Dockerfile
    container_name: grpc-server
    image: "grpc-server:grpc-server"
    ports:
      - "50051:50051"
    restart: always
